add check for user.name and user.email

diff --git a/client-hooks/pre-commit b/client-hooks/pre-commit
--- a/client-hooks/pre-commit
+++ b/client-hooks/pre-commit
@@ -5,14 +5,7 @@
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-    against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
-
+#-----------------------------------------------------------------------------
 # Config
 # ------
 # hooks.allownonascii
@@ -31,9 +24,52 @@ allowsymlinks=$(git config hooks.allowsymlinks)
 #    to the repository.
 allowdotsvn=$(git config hooks.allowdotsvn)
 
+#-----------------------------------------------------------------------------
 # Redirect output to stderr.
 exec 1>&2
 
+#-----------------------------------------------------------------------------
+die() {
+        echo 'pre-commit hook failure' 1>&2
+        echo '-----------------------' 1>&2
+        echo '' 1>&2
+        echo "$@" 1>&2
+        exit 1
+}
+
+#-----------------------------------------------------------------------------
+zero='0000000000000000000000000000000000000000'
+
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+    against=HEAD
+else
+	# Initial commit: diff against an empty tree object
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
+
+#-----------------------------------------------------------------------------
+# Check for committer identity.
+advice='
+Use the commands
+
+        git config --global user.name '\''Your Name'\''
+        git config --global user.email '\''you@yourdomain.com'\''
+
+to introduce yourself to Git before committing.'
+
+# Ensure name and email are available.
+git config --get user.name > /dev/null &&
+git config --get user.email > /dev/null ||
+die 'Identity not configured!' "$advice"
+
+# Validate the name and email.
+git config --get user.name | grep ' ' > /dev/null ||
+die 'Set user.name to your Real Name (with a space), not a userid.' "$advice"
+git config --get user.email | grep '^[^@]*@[^@]*$' > /dev/null ||
+die 'Set user.email to an email address (userid@validdomain.com).' "$advice"
+
+#-----------------------------------------------------------------------------
 # Cross platform projects tend to avoid non-ascii filenames; prevent
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
@@ -60,6 +96,7 @@ then
     exit 1
 fi
 
+#-----------------------------------------------------------------------------
 # Check that transaction will not create files/folders
 # whose name differ only by case (illegal on Windows).
 # check for names that already exist but only differ in case
@@ -78,6 +115,7 @@ then
     exit 1
 fi 
 
+#-----------------------------------------------------------------------------
 # Reject Unix symbolic links, which are not valid (in fact: ignored) on Windows.
 if [ "$allowsymlinks" != "true" ] &&
     test $(git ls-files -s | awk '/120000/{print $4}' | wc -l) != 0
@@ -96,6 +134,7 @@ then
     exit 1
 fi
 
+#-----------------------------------------------------------------------------
 # Check that transaction will not create olders
 # whose name is .svn
 if [ "$allowdotsvn" != "true" ]
@@ -114,8 +153,9 @@ then
 #    echo
     exit 1
   fi
-fi 
+fi
 
 
+#-----------------------------------------------------------------------------
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
